[build-system]
requires = ["uv_build"]
build-backend = "uv_build"

[project]
name = "seeg-utilities"
description = "Miscellaneous utilities to work with sEEG data"
readme = "README.md"
requires-python = ">=3.14"
license = "GPL-3.0-or-later"
license-files = ["LICENSE"]
authors = [
    { name = "Raj Magesh Gauthaman", email = "seeg-utilities@raj-magesh.org" },
]
keywords = [
    "sEEG",
    "contact locator",
    "RippleNeuroMed control",
    "CT to MRI (T1w) alignment",
    "DICOM to NIfTI conversion",
    "electrode metadata",
]
classifiers = [
    "Development Status :: 4 - Beta",
    "Intended Audience :: Science/Research",
    "Natural Language :: English",
    "Operating System :: POSIX :: Linux",
    "Programming Language :: Python :: 3",
    "Topic :: Scientific/Engineering",
    "Typing :: Typed",
]
urls = { repository = "https://codeberg.org/raj-magesh/seeg-utilities" }
dependencies = [
    "loguru",
    "numpy",
    "pandas",
    "scipy",
    "mne",
    "nibabel",
    "dipy",
    "k3d",
    # "dcm2niix",               # FIXME when cmake on cluster gets better
    "heudiconv[all]",
    "matplotlib",
    "hough-3d-line-detector",
]
import-names = ["seeg_utilities"]
version = "0.1.0"

[dependency-groups]
dev = ["ruff", "pytest", "sphinx"]

[tool.uv]
required-environments = [
    "sys_platform == 'linux' and platform_machine == 'x86_64'",
]

[tool.uv.sources]
hough-3d-line-detector = { path = "../../libraries/hough-3d-line-detector", editable = true }
